/**
 * The crisis affordance that renders INTO the keyboard's window (DEBUG-450).
 *
 * WHY IT EXISTS. `RootCrisisButton` cannot be reached while a software keyboard is up:
 * the iOS keyboard renders in `UIRemoteKeyboardWindow`, a separate `UIWindow` above the
 * app's, so `zIndex: 9999` is as irrelevant to it as it is to an RN `<Modal>`, and at the
 * button's 100pt offset its top edge (156pt) is already inside every shipping iPhone's
 * keyboard frame. No in-tree y-position escapes that — see `crisisButtonGeometry.ts`.
 * `InputAccessoryView` is the one shape that renders above the keyboard, which is why
 * DEBUG-431 ruled it "the shape the constraints permit".
 *
 * IT IS ADDITIVE, NEVER A REPLACEMENT. The root button's geometry and
 * `CRISIS_BUTTON_EXCLUSION_RECT` are untouched, and the root button is NOT hidden or
 * faded while this is up. Coordinating the two would be a fourth instance of the
 * two-list reconciliation failure CLAUDE.md already names twice (`features/guidance/`,
 * `features/consent/`): both controls stay independently correct, so a bug in one can
 * never silently remove the other's coverage.
 *
 * IT NAVIGATES, IT DOES NOT DIAL. `Static988Button`'s direct-dial design is scoped to
 * contexts where the navigator itself is the suspect — crash boundaries, pre-ready
 * windows. This fires during normal operation with a mounted navigator, so it takes
 * `RootCrisisButton`'s shape and reuses the same shared path: the retry-then-fallback in
 * `navigateToCrisisResources` already degrades to a direct 988 dial if the navigator is
 * not ready within 400ms, so the safety property comes for free on the rare path that
 * needs it, without narrowing the destination on the common one.
 *
 * DEPENDENCY-LIGHT, following `Static988Button`'s recorded reasoning: no reanimated
 * (DEBUG-299 shipped a NaN transform that made the crisis button invisible AND inert
 * app-wide), no gesture-handler, no icon packages, no React context. A text label cannot
 * fail to render.
 *
 * THE CHILD IS ALWAYS MOUNTED. Visibility is toggled by height/opacity/pointerEvents,
 * never by rendering `null` — `InputAccessoryView` unmounts entirely at zero children,
 * and re-attaching a native accessory view to an already-focused field is the real RN
 * risk here. Collapsing in place avoids it.
 *
 * ONE INSTANCE PER TextInput, AND NEVER RENDERED DIRECTLY (DEBUG-506). This used to be
 * mounted once at app root on the belief that "RN registers accessory content by nativeID
 * app-wide". That belief was false and the control was inert for its whole shipped life:
 * `RCTInputAccessoryComponentView.mm:66-82` attaches only in `didMoveToWindow`, by a
 * one-shot depth-first search of the window for a `TextInput` carrying `nativeID`. From a
 * root mount that search runs at app launch, when no such input exists, and it can never
 * re-run. Render this ONLY from `CrisisTextInput`, which owns the paired lifecycle and
 * supplies a per-instance `nativeID` — `RCTFindTextInputWithNativeId` returns the FIRST
 * depth-first match, so a shared id silently leaves every input but one uncovered.
 *
 * EVERY INSTANCE MUST BE BYTE-IDENTICAL, and that is a correctness constraint rather than
 * a consistency one. `prepareForRecycle` (same file, 145-150) nils `_textInput` but does
 * not clear the previously-bound field's `inputAccessoryView`, and `_contentView` is
 * created once in `initWithFrame` and never recreated — so a recycled component view can
 * leave field A pointing at the content view it then binds to field B. That is harmless
 * only while the instances are interchangeable. Take no prop that reaches the label, the
 * hint, the role, or the bar's styles.
 */

import React from 'react';
import {
  InputAccessoryView,
  Platform,
  Pressable,
  StyleSheet,
  Text,
  useWindowDimensions,
  View,
} from 'react-native';

import { beginCrisisTap } from '@/features/crisis/services/crisisTapTrace';
import { navigateToCrisisResources } from '@/features/crisis/utils/navigateToCrisisResources';
import { useKeyboardOccludesCrisisButton } from '@/core/hooks/useKeyboardOccludesCrisisButton';
import {
  AX_FONT_SCALE,
  CRISIS_KEYBOARD_ACCESSORY_CONTAINER_TEST_ID,
  CRISIS_KEYBOARD_ACCESSORY_TEST_ID,
} from '@/features/crisis/constants/crisisInputAccessory';
import { colorSystem, semantic, spacing, borderRadius, TOUCH_TARGETS } from '@/core/theme';

interface CrisisKeyboardAccessoryProps {
  /**
   * The id shared with exactly one `TextInput`. Generated by `CrisisTextInput`; never
   * supplied by a call site, and never shared between instances.
   */
  nativeID: string;
}

/**
 * Rendered only by `CrisisTextInput`, as the second half of one mount. See the header for
 * why this must not be mounted at app root and why it takes no presentational props.
 */
export const CrisisKeyboardAccessory: React.FC<CrisisKeyboardAccessoryProps> = ({
  nativeID,
}) => {
  const occluded = useKeyboardOccludesCrisisButton();
  // Chrome, not content: at AX content sizes the bar sheds padding so the label keeps its
  // full growth. This is the opposite of `maxFontSizeMultiplier`, which the house ruled
  // against on crisis labels (CrisisResourcesScreen.tsx:778-781) and which stays refused.
  const { fontScale } = useWindowDimensions();
  const axRange = fontScale >= AX_FONT_SCALE;

  // InputAccessoryView is iOS-only in RN. Android needs no equivalent: adjustResize
  // repositions the root button above the IME by itself.
  if (Platform.OS !== 'ios') return null;

  const handlePress = (): void => {
    // INFRA-297 ordering, matching CollapsibleCrisisButton's
    // `beginCrisisTap → navigate → cosmetics`. Opens the tap→render measurement; must
    // precede the navigate, because you cannot measure tap→render starting after it.
    beginCrisisTap('keyboard_accessory');

    // THE CRISIS ACTION. First, unconditional, synchronous, outside every telemetry
    // construct. Same shared path the root button takes.
    navigateToCrisisResources('keyboard_accessory', 'CrisisKeyboardAccessory');
  };

  return (
    <InputAccessoryView nativeID={nativeID}>
      <View
        testID={CRISIS_KEYBOARD_ACCESSORY_CONTAINER_TEST_ID}
        style={[
          styles.bar,
          occluded ? styles.barVisible : styles.barCollapsed,
          occluded && axRange ? styles.barVisibleAx : null,
        ]}
        pointerEvents={occluded ? 'auto' : 'none'}
        // Hidden from assistive tech when collapsed, so a screen-reader user does not
        // land on a zero-height control they cannot act on.
        accessibilityElementsHidden={!occluded}
        importantForAccessibility={occluded ? 'yes' : 'no-hide-descendants'}
      >
        <Pressable
          testID={CRISIS_KEYBOARD_ACCESSORY_TEST_ID}
          onPress={handlePress}
          style={styles.button}
          hitSlop={spacing[8]}
          accessibilityRole="button"
          // Identical to the root button's, deliberately: the same affordance in a
          // different place should not announce itself as a different control.
          accessibilityLabel="I need support"
          accessibilityHint="Tap for immediate access to crisis resources"
        >
          <Text style={styles.label}>I need support</Text>
        </Pressable>
      </View>
    </InputAccessoryView>
  );
};

const styles = StyleSheet.create({
  bar: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'flex-end',
    backgroundColor: semantic.background.secondary,
    overflow: 'hidden',
  },
  barVisible: {
    // The padding is clearance around the control, not the target itself — the
    // button below carries its own REAL height, per the same WCAG 2.5.5 reasoning
    // Static988Button records (hitSlop enlarges touch, not the visible target).
    paddingVertical: spacing[8],
    paddingHorizontal: spacing[16],
  },
  barVisibleAx: {
    // DEBUG-506 constraint 21. At AX content sizes the label is allowed to grow without
    // limit and the bar gives up its own decoration to pay for it. Never the reverse:
    // no maxFontSizeMultiplier, no numberOfLines, no ellipsizeMode on a crisis label.
    paddingVertical: 0,
    paddingHorizontal: spacing[8],
  },
  barCollapsed: {
    height: 0,
    paddingVertical: 0,
    opacity: 0,
  },
  button: {
    // `large`, not `minimum`: accessibility.ts:296-300 names 56 as the size to "Apply to:
    // Crisis buttons", and CrisisResourcesScreen.tsx:793-795 already records that ruling
    // for its own footer. This control carries the same contract.
    minHeight: TOUCH_TARGETS.large,
    justifyContent: 'center',
    paddingHorizontal: spacing[16],
    borderRadius: borderRadius.medium,
    backgroundColor: colorSystem.status.critical,
    // The bar sets `overflow: 'hidden'` (load-bearing for the height-0 collapse), so an
    // auto-sized child that outgrows the row is CLIPPED rather than wrapped — the
    // DEBUG-390 shape, and reachable from ordinary iOS Settings well below AX5. Let the
    // button shrink and the label wrap instead.
    maxWidth: '100%',
    flexShrink: 1,
  },
  label: {
    color: colorSystem.base.white,
    fontWeight: '600',
    flexShrink: 1,
  },
});

export default CrisisKeyboardAccessory;
