#!/bin/bash

# Remove migration-related test files (cleanup artifacts)
echo "Removing migration-related test artifacts..."

# Migration test files to remove
rm -f "/Users/max/Development/active/fullmind/app/__tests__/unit/CrisisButton.migration.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/clinical/sqlite-migration-clinical.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/clinical/crisis-access-during-migration.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/clinical/clinical-support-migration-safety.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/performance/sqlite-migration-performance.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/performance/pressable-migration-performance-validation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/integration/pressable-migration-integration-validation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/integration/comprehensive-migration-integration.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/accessibility/pressable-migration-accessibility-compliance.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/clinical/phase3-pressable-migration-therapeutic.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/clinical/phase3-todays-value-screen-migration-validation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/production-validation/critical-migration-validation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/src/store/migration/__tests__/CrisisPerformanceValidation.test.ts"

# Validation test files (cleanup artifacts)
rm -f "/Users/max/Development/active/fullmind/app/__tests__/unit/validation.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/unit/CrisisButtonReactValidation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/crisis/comprehensive-crisis-sync-validation.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/security/comprehensive-security-testing-validation.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/security/comprehensive-security-validation.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/security/webhook-security-validation.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/clinical/comprehensive-clinical-validation.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/clinical/clinical-workflow-integration-validation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/clinical/crisis-detection-pressable-validation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/clinical/crisis-detection-validation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/clinical/cross-platform-performance-validation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/integration/integration-validation-summary.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/integration/regression-testing-validation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/payment/PaymentComponentMigrationValidation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/payment/PaymentIntegrationFlowValidation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/performance/PaymentUIPerformanceValidation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/performance/comprehensive-monitoring-validation.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/performance/new-architecture-validation.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/accessibility/PaymentAccessibilityValidation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/src/services/security/__tests__/PaymentSyncSecurityValidation.comprehensive.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/src/services/security/__tests__/ZeroPIIValidationFramework.integration.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/src/types/__tests__/button-type-validation.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/src/types/__tests__/clinical-type-safety-validation.test.ts"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/performance/state-management-optimization/clinical-accuracy-validation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/performance/state-management-optimization/performance-validation.test.tsx"
rm -f "/Users/max/Development/active/fullmind/app/__tests__/security/phase7b-security-configuration-consolidation.test.ts"

echo "Migration and validation test artifacts removed."